name: test img

on: push
permissions:
  contents: read

jobs:
  testimage:
    name: test img
    runs-on: ubuntu-latest
    steps:
      # environment
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      # 登录到docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # prepare image tags
      - name: Prepare Image Tags
        run: |
          echo "TAG_PF=paddleflow/ubuntu-python38:latest" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfiles/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.TAG_PF }}

